apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cta-ingress
  namespace: cta-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cta-frontend.com
    secretName: cta-fe-tls
  rules:
  - host: cta-frontend.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cta-service
            port:
              number: 80
